version: '3'
services:
  config-service:
    build:
      context: ./ConfigurationService
#    ports:
#      - "8088:8088"

  discovery-service:
    build:
      context: ./DiscoveryService
    ports:
      - "8061:8061"
    links:
      - config-service

  gateway-service:
    build:
      context: ./GatewayService
    ports:
      - "8060:8060"
    links:
      - config-service
      - discovery-service
      - book-service

  book-service:
    build:
      context: ./BookService
#    ports:
#      - "8098:8098"
    links:
      - config-service
      - discovery-service
    depends_on:
      - book-database
    volumes:
       - /home/grzegorz/Documents/covers:/covers


  authorization-service:
    build:
      context: ./AuthorizationService
#    ports:
#      - "8099:8099"
    links:
      - config-service
      - discovery-service
    depends_on:
      - authorization-database

  authorization-database:
    build:
      context: .
      dockerfile: AuthDbDockerfile
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - DATABASE_PORT=3306

  book-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"