server:
  port: 8099

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://authorization-database:3306/userAuthorization?useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

security:
  user:
    name: root
    password: pswd
  oauth2:
    client:
      client-id: acme
      client-secret: secret