server:
  port: 8098

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

spring:
  data:
    mongodb:
      host: book-database
      port: 27017
      authentication-database: admin
      username: root
      password: password
      database: booksDb

applicationKey: AIzaSyBrT9VTZN1q2YtQ9mwiFiv3HMaeAmVmthM
applicationCx: 003630389706661019147:i5a1vmvqv4m
connectionTimeout: 100000