server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

zuul:
  routes:
    user-service:
      path: /userservice/**
      sensitiveHeaders:
      serviceId: user-service
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-server



#to
#  security:
#    user:
#      name: root
#      password: pswd
#security:
#    oauth2:
#      client:
#        accessTokenUri: http://authorization-service:8099/uua/oauth/token
#        userAuthorizationUri: http://authorization-service:8099/uua/oauth/authorize
#        clientAuthenticationScheme: form
#      resource:
#        userInfoUri: http://authorization-service:8099/uaa/user
#        preferTokenInfo: false