server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

zuul:
  routes:
    user-service:
      path: /book/**
      sensitiveHeaders:
      serviceId: book-service
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: authorization-service
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

ribbon:
   ReadTimeout: 30000
hystrix:
  command:
    default:
      execution:
          isolation:
              thread:
                timeoutInMilliseconds: 90000



security:
  oauth2:
    client:
      accessTokenUri: http://authorization-service:8099/oauth/token
      client-id: client
      client-secret: secred
    resource:
      userInfoUri: http://authorization-service:8099/user