server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

zuul:
  routes:
    user-service:
      path: /book/**
      sensitiveHeaders:
      serviceId: book-service
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-service
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

ribbon:
   ReadTimeout: 30000
hystrix:
  command:
    default:
      execution:
          isolation:
             thread:
                timeoutInMilliseconds: 90000


#to
#  security:
#    user:
#      name: root
#      password: pswd
#security:
#    oauth2:
#      client:
#        accessTokenUri: http://authorization-service:8099/uua/oauth/token
#        userAuthorizationUri: http://authorization-service:8099/uua/oauth/authorize
#        clientAuthenticationScheme: form
#      resource:
#        userInfoUri: http://authorization-service:8099/uaa/user
#        preferTokenInfo: false